apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-stack.fullname" . }}-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: {{ include "example-stack.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "example-stack.fullname" . }}-backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.port }}
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mariadb
            - name: DB_HOST
              value: {{ include "example-stack.fullname" . }}-database
            - name: DB_PORT
              value: "{{ .Values.database.port }}"
            - name: DB_NAME
              value: {{ .Values.database.name }}
            - name: DB_USERNAME
              value: {{ .Values.database.username }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
