apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-stack.fullname" . }}-backend
spec:
  selector:
    app: {{ include "example-stack.fullname" . }}-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
