apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-stack.fullname" . }}-nginx
spec:
  selector:
    app: {{ include "example-stack.fullname" . }}-nginx
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
