spring:
  application:
    name: prd-delivery-backend
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:example_app}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:example}
    password: ${DB_PASSWORD:example}
  liquibase:
    change-log: classpath:db/liquibase/changelog/db.changelog-master.yaml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

workspace:
  name: prd-driven-delivery
