apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-stack.fullname" . }}-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: {{ include "example-stack.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "example-stack.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
